Starting epoch 1/100...
Epoch 1:   0%|                                                                                                       | 0/42476 [00:00<?, ?it/s]Exception in thread Thread-5 (_pin_memory_loop):
Global Max: 0.12886852025985718
Traceback (most recent call last):                                                                            | 19/188 [02:39<22:48,  8.10s/it]
  File "/root/miniconda3/envs/rewas/lib/python3.10/threading.py", line 1016, in _bootstrap_inner
    self.run()
  File "/root/miniconda3/envs/rewas/lib/python3.10/threading.py", line 953, in run
    self._target(*self._args, **self._kwargs)
  File "/root/miniconda3/envs/rewas/lib/python3.10/site-packages/torch/utils/data/_utils/pin_memory.py", line 59, in _pin_memory_loop
    do_one_step()
  File "/root/miniconda3/envs/rewas/lib/python3.10/site-packages/torch/utils/data/_utils/pin_memory.py", line 35, in do_one_step
    r = in_queue.get(timeout=MP_STATUS_CHECK_INTERVAL)
  File "/root/miniconda3/envs/rewas/lib/python3.10/multiprocessing/queues.py", line 122, in get
    return _ForkingPickler.loads(res)
  File "/root/miniconda3/envs/rewas/lib/python3.10/site-packages/torch/multiprocessing/reductions.py", line 541, in rebuild_storage_fd
    fd = df.detach()
  File "/root/miniconda3/envs/rewas/lib/python3.10/multiprocessing/resource_sharer.py", line 57, in detach
    with _resource_sharer.get_connection(self._id) as conn:
  File "/root/miniconda3/envs/rewas/lib/python3.10/multiprocessing/resource_sharer.py", line 86, in get_connection
    c = Client(address, authkey=process.current_process().authkey)
  File "/root/miniconda3/envs/rewas/lib/python3.10/multiprocessing/connection.py", line 502, in Client
    c = SocketClient(address)
  File "/root/miniconda3/envs/rewas/lib/python3.10/multiprocessing/connection.py", line 630, in SocketClient
    s.connect(address)
FileNotFoundError: [Errno 2] No such file or directory
Evaluating:  10%|█████████▍                                                                                   | 19/188 [02:52<25:35,  9.08s/it]
Exception ignored in: <function _MultiProcessingDataLoaderIter.__del__ at 0x7f187672e680>
Traceback (most recent call last):
  File "/root/miniconda3/envs/rewas/lib/python3.10/site-packages/torch/utils/data/dataloader.py", line 1604, in __del__
    self._shutdown_workers()
  File "/root/miniconda3/envs/rewas/lib/python3.10/site-packages/torch/utils/data/dataloader.py", line 1550, in _shutdown_workers
    self._pin_memory_thread.join()
  File "/root/miniconda3/envs/rewas/lib/python3.10/threading.py", line 1096, in join
    self._wait_for_tstate_lock()
  File "/root/miniconda3/envs/rewas/lib/python3.10/threading.py", line 1116, in _wait_for_tstate_lock
    if lock.acquire(block, timeout):
KeyboardInterrupt:
Epoch 1:   0%|                                                                                                       | 0/42476 [04:22<?, ?it/s]
Traceback (most recent call last):
  File "/workspace/rewas/./train_miil.py", line 329, in <module>
    main(args)
  File "/workspace/rewas/./train_miil.py", line 248, in main
    avg_loss1, avg_loss2, avg_loss3, avg_iou1, avg_iou2, avg_iou3 = evaluate(phi, video_encoder, test_loader, synchformer_cfg.training.use_half_precision)
  File "/workspace/rewas/evaluate_cam.py", line 90, in evaluate
    valid_pred_cam_mask = pred_cam_mask.reshape(-1)
KeyboardInterrupt
